# Pester tests for the parts of the bootstrap that can be checked without changing a PC: the
# package list, the extension list parsing, the pointer files and plan mode end to end.

BeforeAll {
    $script:Root = Split-Path -Parent $PSScriptRoot
    $lib = Join-Path $script:Root 'bootstrap\lib'
    . (Join-Path $lib 'common.ps1')
    . (Join-Path $lib 'winget.ps1')
    . (Join-Path $lib 'vscode.ps1')
    $script:PlanMode = $false
}

Describe 'package list' {
    It 'is valid winget import JSON with unique publisher.name identifiers' {
        $ids = Get-PackageIds
        $ids.Count | Should -BeGreaterThan 30
        ($ids | Sort-Object -Unique).Count | Should -Be $ids.Count
        $ids | ForEach-Object { $_ | Should -Match '^[A-Za-z0-9-]+\.[A-Za-z0-9.+-]+$' }
    }

    It 'covers the everyday tools the shell profile expects' {
        $ids = Get-PackageIds
        foreach ($id in 'Git.Git', 'GitHub.cli', 'Microsoft.PowerShell', 'Starship.Starship', 'ajeetdsouza.zoxide', 'BurntSushi.ripgrep.MSVC', 'Microsoft.VisualStudioCode') {
            $ids | Should -Contain $id
        }
    }
}

Describe 'Get-WantedExtensions' {
    It 'strips pinned versions, comments and blank lines and lowercases names' {
        $list = Join-Path $TestDrive 'extensions.txt'
        Set-Content $list @('// editors', 'EditorConfig.EditorConfig@0.16.4', '', '# notes', 'eamodio.gitlens')
        Get-WantedExtensions -ListPath $list | Should -Be @('editorconfig.editorconfig', 'eamodio.gitlens')
    }
}

Describe 'Set-PointerFile' {
    It 'writes the pointer when no file exists' {
        $path = Join-Path $TestDrive 'new\profile.ps1'
        Set-PointerFile -Path $path -Content '. "C:\dotfiles\profile.ps1"'
        Get-Content -Raw $path | Should -Match 'dotfiles'
    }

    It 'keeps a different existing file as a backup instead of overwriting it' {
        $path = Join-Path $TestDrive 'existing\profile.ps1'
        New-Item -ItemType Directory -Force -Path (Split-Path $path) | Out-Null
        Set-Content $path '# my own profile'
        Set-PointerFile -Path $path -Content '. "C:\dotfiles\profile.ps1"'
        (Get-ChildItem (Split-Path $path) -Filter 'profile.ps1.backup-*').Count | Should -Be 1
    }

    It 'leaves a file that already points at the dotfiles untouched' {
        $path = Join-Path $TestDrive 'same\profile.ps1'
        New-Item -ItemType Directory -Force -Path (Split-Path $path) | Out-Null
        Set-Content $path '. "C:\dotfiles\profile.ps1"'
        Set-PointerFile -Path $path -Content '. "C:\dotfiles\profile.ps1"'
        (Get-ChildItem (Split-Path $path)).Count | Should -Be 1
    }
}

Describe 'Windows Terminal schemes' {
    BeforeAll {
        . (Join-Path $script:Root 'bootstrap\lib\common.ps1')
        . (Join-Path $script:Root 'bootstrap\lib\configs.ps1')
        $script:PlanMode = $false
    }

    It 'sets the light and dark pair and bold text, keeping comments out of the way' {
        $path = Join-Path $TestDrive 'settings.json'
        Set-Content $path "// generated by Windows Terminal`n{ ""profiles"": { ""defaults"": {}, ""list"": [] } }"
        Set-TerminalScheme -SettingsPath $path 6>$null
        $saved = Get-Content -Raw $path | ConvertFrom-Json
        $saved.profiles.defaults.colorScheme.dark | Should -Be 'High Contrast Dark'
        $saved.profiles.defaults.colorScheme.light | Should -Be 'High Contrast Light'
        $saved.profiles.defaults.intenseTextStyle | Should -Be 'bold'
    }

    It 'leaves a file that already uses the pair untouched' {
        $path = Join-Path $TestDrive 'done.json'
        Set-Content $path '{ "profiles": { "defaults": { "colorScheme": { "dark": "High Contrast Dark", "light": "High Contrast Light" } } } }'
        Set-TerminalScheme -SettingsPath $path 6>$null
        (Get-ChildItem $TestDrive -Filter 'done.json.backup*').Count | Should -Be 0
    }
}

Describe 'plan mode' {
    It 'runs every stage and changes nothing' {
        $env:WINDOWS_BOOTSTRAP_ALLOW_ANY_OS = '1'
        $env:WINDOWS_BOOTSTRAP_REPOS_DIR = Join-Path $TestDrive 'repos'
        $output = & (Join-Path $script:Root 'bootstrap\bootstrap.ps1') -Plan -Skip vscode 6>&1 | Out-String
        foreach ($stage in 'winget', 'dotfiles', 'git', 'configs', 'settings', 'wsl') {
            $output | Should -Match "Completed stage: $stage"
        }
        $output | Should -Match 'Would clone dotfiles into'
        Test-Path $env:WINDOWS_BOOTSTRAP_REPOS_DIR | Should -BeFalse
    }
}
